import { router } from 'expo-router';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { Alert,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { BrandHeader } from '@/components/BrandHeader';
import { Button,Eyebrow,Loading,Title } from '@/components/ui';
import { useAuth } from '@/contexts/AuthContext';
import { deleteAdminContribution,deleteAdminPlace,deleteAdminReport,loadAdminSnapshot,setAdminUserRole,updateAdminContribution,updateAdminPlace,updateAdminReport,type AdminSnapshot } from '@/services/admin';
import { colors,radius,shadow } from '@/theme';

type Tab='overview'|'places'|'contributions'|'reports'|'users';
const empty:AdminSnapshot={places:[],contributions:[],reports:[],users:[]};
const tabNames:Record<Tab,string>={overview:'Vue d’ensemble',places:'Lieux',contributions:'Contributions',reports:'Signalements',users:'Utilisateurs'};
function date(value:string){return new Date(value).toLocaleDateString('fr-FR')}
export default function Admin(){
  const {user,role,loading:authLoading}=useAuth(); const [tab,setTab]=useState<Tab>('overview'); const [data,setData]=useState<AdminSnapshot>(empty); const [loading,setLoading]=useState(true);
  const allowed=role==='admin'||role==='moderator';
  const load=useCallback(async()=>{if(!allowed)return;setLoading(true);try{setData(await loadAdminSnapshot(role))}catch(error){Alert.alert('Chargement impossible',error instanceof Error?error.message:'Erreur inconnue')}finally{setLoading(false)}},[allowed,role]);
  useEffect(()=>{void load()},[load]);
  const metrics=useMemo(()=>({places:data.places.filter(p=>p.publish_status==='pending_review').length,contributions:data.contributions.filter(c=>['pending','in_review'].includes(c.status)).length,reports:data.reports.filter(r=>['open','in_review'].includes(r.status)).length,moderators:data.users.filter(u=>u.role==='moderator').length}),[data]);
  if(authLoading)return <Loading/>; if(!user||!allowed)return <View style={s.denied}><BrandHeader/><Eyebrow>ESPACE ÉQUIPE</Eyebrow><Title>Accès réservé à l’équipe BLACKSPOT YOU.</Title><Text style={s.muted}>Connectez-vous avec un compte modérateur ou administrateur.</Text><Button title="Retour au profil" onPress={()=>router.replace('/(tabs)/profile')}/></View>;
  const run=async(fn:()=>Promise<void>,success:string)=>{try{await fn();await load();Alert.alert('Terminé',success)}catch(error){Alert.alert('Action impossible',error instanceof Error?error.message:'Erreur inconnue')}};
  const confirmDelete=(title:string,fn:()=>Promise<void>)=>Alert.alert('Suppression définitive',title,[{text:'Annuler',style:'cancel'},{text:'Supprimer',style:'destructive',onPress:()=>void run(fn,'Élément supprimé.')}]);
  return <View style={s.page}><ScrollView contentContainerStyle={s.content}>
    <BrandHeader/><View style={s.heading}><Eyebrow>{role==='admin'?'ADMINISTRATION':'MODÉRATION'}</Eyebrow><Title>{tabNames[tab]}</Title><Text style={s.muted}>Gestion native sécurisée · {user.email}</Text></View>
    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.tabs}>{(['overview','places','contributions','reports',...(role==='admin'?['users']:[])] as Tab[]).map(id=><Pressable key={id} onPress={()=>setTab(id)} style={[s.tab,tab===id&&s.tabOn]}><Text style={[s.tabText,tab===id&&s.tabTextOn]}>{tabNames[id]}</Text></Pressable>)}</ScrollView>
    {loading?<Loading/>:null}
    {!loading&&tab==='overview'?<View style={s.block}><View style={s.metricGrid}><Metric value={metrics.places} label="Lieux à vérifier"/><Metric value={metrics.contributions} label="Contributions"/><Metric value={metrics.reports} label="Signalements"/>{role==='admin'?<Metric value={metrics.moderators} label="Modérateurs"/>:null}</View><View style={s.info}><Text style={s.infoTitle}>{role==='admin'?'Plein contrôle administrateur':'File de modération'}</Text><Text style={s.infoCopy}>{role==='admin'?'Vous pouvez publier, modifier les statuts, supprimer des contenus et gérer les rôles depuis l’application.':'Vous pouvez traiter les lieux, contributions et signalements selon vos droits de modération.'}</Text></View><Button title="Créer / proposer un lieu" onPress={()=>router.push('/propose')}/><Button title="Actualiser les données" variant="secondary" onPress={()=>void load()}/></View>:null}
    {!loading&&tab==='places'?<View style={s.block}>{data.places.map(item=><View key={item.id} style={s.card}><View style={s.cardTop}><View style={s.flex}><Text style={s.cardTitle}>{item.name}</Text><Text style={s.meta}>{item.city} · {item.address_line??'adresse non renseignée'} · {date(item.created_at)}</Text></View><Status text={item.publish_status}/></View><Text style={s.secondaryStatus}>{item.public_status.replaceAll('_',' ')}</Text><View style={s.actions}><Action text="Publier" onPress={()=>void run(()=>updateAdminPlace(item.id,{publish_status:'published',public_status:item.public_status==='unclassified'?'community_recommended':item.public_status,published_at:new Date().toISOString()}),'Lieu publié.')}/><Action text="Vérifier" onPress={()=>void run(()=>updateAdminPlace(item.id,{publish_status:'pending_review',public_status:'under_review'}),'Lieu placé en vérification.')}/><Action text="Rejeter" onPress={()=>void run(()=>updateAdminPlace(item.id,{publish_status:'rejected'}),'Lieu rejeté.')}/>{role==='admin'?<Action danger text="RED SPOT" onPress={()=>void run(()=>updateAdminPlace(item.id,{publish_status:'published',public_status:'incident_documented',published_at:new Date().toISOString()}),'RED SPOT validé.')}/>:null}{role==='admin'?<Action danger text="Supprimer" onPress={()=>confirmDelete(`Supprimer définitivement « ${item.name} » et les données liées ?`,()=>deleteAdminPlace(item.id))}/>:null}</View></View>)}{!data.places.length?<Text style={s.empty}>Aucun lieu accessible.</Text>:null}</View>:null}
    {!loading&&tab==='contributions'?<View style={s.block}>{data.contributions.map(item=><View key={item.id} style={s.card}><View style={s.cardTop}><View style={s.flex}><Text style={s.cardTitle}>{item.title??'Contribution sans titre'}</Text><Text style={s.meta}>{date(item.created_at)}</Text></View><Status text={item.status}/></View><Text numberOfLines={5} style={s.body}>{item.body}</Text><View style={s.actions}><Action text="Approuver" onPress={()=>void run(()=>updateAdminContribution(item.id,'approved'),'Contribution approuvée. Les B-coins éventuels ont été crédités.')}/><Action text="Précisions" onPress={()=>void run(()=>updateAdminContribution(item.id,'info_requested'),'Précisions demandées.')}/><Action text="Rejeter" onPress={()=>void run(()=>updateAdminContribution(item.id,'rejected'),'Contribution rejetée.')}/>{role==='admin'?<Action danger text="Masquer" onPress={()=>void run(()=>updateAdminContribution(item.id,'hidden'),'Contribution masquée.')}/>:null}{role==='admin'?<Action danger text="Supprimer" onPress={()=>confirmDelete('Supprimer définitivement cette contribution ?',()=>deleteAdminContribution(item.id))}/>:null}</View></View>)}{!data.contributions.length?<Text style={s.empty}>Aucune contribution accessible.</Text>:null}</View>:null}
    {!loading&&tab==='reports'?<View style={s.block}>{data.reports.map(item=><View key={item.id} style={s.card}><View style={s.cardTop}><View style={s.flex}><Text style={s.cardTitle}>{item.reason.replaceAll('_',' ')}</Text><Text style={s.meta}>{item.target_type} · {date(item.created_at)}</Text></View><Status text={item.status}/></View>{item.details?<Text style={s.body}>{item.details}</Text>:null}<View style={s.actions}><Action text="Prendre" onPress={()=>void run(()=>updateAdminReport(item.id,'in_review'),'Signalement pris en charge.')}/><Action text="Résoudre" onPress={()=>void run(()=>updateAdminReport(item.id,'resolved'),'Signalement résolu.')}/><Action text="Classer" onPress={()=>void run(()=>updateAdminReport(item.id,'dismissed'),'Signalement classé.')}/>{role==='admin'?<Action danger text="Supprimer" onPress={()=>confirmDelete('Supprimer définitivement ce signalement ?',()=>deleteAdminReport(item.id))}/>:null}</View></View>)}{!data.reports.length?<Text style={s.empty}>Aucun signalement accessible.</Text>:null}</View>:null}
    {!loading&&tab==='users'&&role==='admin'?<View style={s.block}><View style={s.info}><Text style={s.infoTitle}>Rôles de l’équipe</Text><Text style={s.infoCopy}>L’administrateur reste unique. Vous pouvez nommer ou retirer des modérateurs depuis cette liste.</Text></View>{data.users.map(item=><View key={item.user_id} style={s.user}><View style={s.flex}><Text style={s.cardTitle}>{item.display_name}</Text><Text style={s.meta}>{item.email} · {date(item.created_at)}</Text></View>{item.role==='admin'?<Status text="admin"/>:<View style={s.actions}><Status text={item.role}/>{item.role==='member'?<Action text="Nommer modérateur" onPress={()=>void run(()=>setAdminUserRole(item.user_id,'moderator'),`${item.display_name} est modérateur.`)}/>:<Action danger text="Retirer modération" onPress={()=>void run(()=>setAdminUserRole(item.user_id,'member'),`${item.display_name} est utilisateur.`)}/>}</View>}</View>)}</View>:null}
  </ScrollView></View>
}
function Metric({value,label}:{value:number;label:string}){return <View style={s.metric}><Text style={s.metricValue}>{value}</Text><Text style={s.metricLabel}>{label}</Text></View>}
function Status({text}:{text:string}){return <View style={s.status}><Text style={s.statusText}>{text.replaceAll('_',' ')}</Text></View>}
function Action({text,onPress,danger=false}:{text:string;onPress:()=>void;danger?:boolean}){return <Pressable onPress={onPress} style={({pressed})=>[s.action,danger&&s.actionDanger,pressed&&{opacity:.7}]}><Text style={[s.actionText,danger&&s.actionDangerText]}>{text}</Text></Pressable>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{padding:20,paddingTop:26,paddingBottom:60,gap:16},denied:{flex:1,backgroundColor:colors.canvas,padding:20,paddingTop:58,gap:16},heading:{gap:6},muted:{color:colors.muted,fontSize:13,lineHeight:19},tabs:{gap:8,paddingRight:10},tab:{height:40,borderRadius:radius.pill,borderWidth:1,borderColor:colors.border,backgroundColor:colors.white,paddingHorizontal:14,justifyContent:'center'},tabOn:{backgroundColor:colors.black,borderColor:colors.black},tabText:{fontSize:12,fontWeight:'800',color:colors.ink},tabTextOn:{color:colors.white},block:{gap:12},metricGrid:{flexDirection:'row',flexWrap:'wrap',gap:10},metric:{width:'47.8%',minHeight:112,borderRadius:radius.lg,backgroundColor:colors.black,padding:16,justifyContent:'space-between'},metricValue:{fontSize:34,fontWeight:'950',color:colors.white},metricLabel:{fontSize:12,color:'rgba(255,255,255,.62)',fontWeight:'700'},info:{borderRadius:radius.lg,backgroundColor:colors.lilac,padding:16},infoTitle:{fontSize:16,fontWeight:'900',color:colors.purpleDark},infoCopy:{fontSize:12.5,lineHeight:18,color:colors.muted,marginTop:5},card:{borderRadius:radius.lg,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,padding:16,gap:10,...shadow},cardTop:{flexDirection:'row',alignItems:'flex-start',justifyContent:'space-between',gap:10},flex:{flex:1},cardTitle:{fontSize:16,fontWeight:'900',color:colors.ink},meta:{fontSize:10.5,color:colors.muted,marginTop:4},secondaryStatus:{fontSize:11,color:colors.purpleDark,fontWeight:'800',textTransform:'capitalize'},body:{fontSize:13,lineHeight:19,color:colors.muted},status:{alignSelf:'flex-start',backgroundColor:colors.lilac,borderRadius:radius.pill,paddingVertical:5,paddingHorizontal:8},statusText:{fontSize:10,fontWeight:'850',color:colors.purpleDark,textTransform:'capitalize'},actions:{flexDirection:'row',flexWrap:'wrap',gap:7,alignItems:'center'},action:{borderRadius:radius.pill,backgroundColor:colors.black,paddingVertical:8,paddingHorizontal:11},actionDanger:{backgroundColor:'#FCE8E7'},actionText:{color:colors.white,fontSize:10.5,fontWeight:'850'},actionDangerText:{color:colors.danger},user:{borderRadius:radius.lg,backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,padding:15,flexDirection:'row',alignItems:'center',gap:10},empty:{color:colors.muted,textAlign:'center',padding:24}});
