import { router } from 'expo-router';
import { useCallback,useEffect,useState } from 'react';
import { Alert,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { BrandHeader } from '@/components/BrandHeader';
import { Button,Empty,Eyebrow,Loading,Title } from '@/components/ui';
import { useAuth } from '@/contexts/AuthContext';
import { getBCoinWallet,listBCoinLedger,listBCoinRewards,redeemBCoinReward } from '@/services/bcoins';
import { colors,radius,shadow } from '@/theme';
import type { BCoinLedgerEntry,BCoinReward,BCoinWallet } from '@/types';

export default function BCoins(){const {user,loading:authLoading}=useAuth();const [wallet,setWallet]=useState<BCoinWallet|null>(null);const [ledger,setLedger]=useState<BCoinLedgerEntry[]>([]);const [rewards,setRewards]=useState<BCoinReward[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(async()=>{if(!user)return;setLoading(true);try{const [w,l,r]=await Promise.all([getBCoinWallet(user.id),listBCoinLedger(user.id),listBCoinRewards()]);setWallet(w);setLedger(l);setRewards(r)}finally{setLoading(false)}},[user]);useEffect(()=>{void load()},[load]);if(authLoading)return <Loading/>;if(!user)return <View style={s.guest}><BrandHeader/><Eyebrow>B-COINS</Eyebrow><Title>Votre contribution a de la valeur.</Title><Text style={s.copy}>Connectez-vous pour gagner des B-coins lorsque vos lieux et contributions sont validés par l’équipe.</Text><Button title="Se connecter" onPress={()=>router.push('/auth')}/></View>;
const redeem=(reward:BCoinReward)=>Alert.alert('Débloquer cette récompense ?',`${reward.cost} B-coins seront débités de votre solde.`,[{text:'Annuler',style:'cancel'},{text:'Débloquer',onPress:async()=>{try{await redeemBCoinReward(reward.id);Alert.alert('Récompense demandée','Votre demande a bien été enregistrée.');await load()}catch(error){Alert.alert('Impossible',error instanceof Error?error.message:'Réessayez plus tard.')}}}]);
return <ScrollView style={s.page} contentContainerStyle={s.content}><BrandHeader/><View style={s.hero}><Eyebrow inverse>MON PORTEFEUILLE</Eyebrow><Text style={s.balance}>{wallet?.balance??0}</Text><Text style={s.unit}>B-coins disponibles</Text><Text style={s.lifetime}>{wallet?.lifetime_earned??0} gagnés depuis votre arrivée</Text></View><View style={s.rules}><Text style={s.rulesTitle}>Comment en gagner ?</Text><View style={s.rule}><Text style={s.ruleAmount}>+25</Text><Text style={s.ruleCopy}>quand un lieu que vous proposez est validé</Text></View><View style={s.rule}><Text style={s.ruleAmount}>+10</Text><Text style={s.ruleCopy}>quand une contribution à un lieu existant est validée</Text></View><Text style={s.note}>Les B-coins sont des points de fidélité internes, sans valeur monétaire et non convertibles en euros.</Text></View><View style={s.sectionHead}><Text style={s.section}>Récompenses partenaires</Text><Text style={s.meta}>{rewards.length}</Text></View>{loading?<Loading/>:rewards.length?rewards.map(reward=><Pressable key={reward.id} onPress={()=>redeem(reward)} style={s.reward}><View><Text style={s.partner}>{reward.partner_name??'BLACKSPOT YOU'}</Text><Text style={s.rewardTitle}>{reward.title}</Text><Text style={s.rewardCopy}>{reward.description}</Text></View><View style={s.cost}><Text style={s.costText}>{reward.cost} B</Text></View></Pressable>):<Empty text="Les premières récompenses apparaîtront ici dès qu’une collaboration sera activée."/>}<View style={s.sectionHead}><Text style={s.section}>Historique</Text><Text style={s.meta}>{ledger.length}</Text></View>{ledger.map(entry=><View key={entry.id} style={s.entry}><View style={s.entryText}><Text style={s.entryReason}>{entry.reason}</Text><Text style={s.entryDate}>{new Date(entry.created_at).toLocaleDateString('fr-FR')}</Text></View><Text style={[s.entryAmount,entry.amount<0&&s.negative]}>{entry.amount>0?'+':''}{entry.amount}</Text></View>)}</ScrollView>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{padding:20,paddingTop:26,paddingBottom:50,gap:16},guest:{flex:1,backgroundColor:colors.canvas,padding:20,paddingTop:58,gap:16},copy:{color:colors.muted,lineHeight:23,fontSize:15},hero:{borderRadius:radius.xl,backgroundColor:colors.black,padding:22,overflow:'hidden'},balance:{color:colors.white,fontSize:68,fontWeight:'950',lineHeight:76,marginTop:8},unit:{color:colors.white,fontSize:17,fontWeight:'850'},lifetime:{color:'rgba(255,255,255,.55)',fontSize:12,marginTop:8},rules:{backgroundColor:colors.white,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,padding:17,gap:11,...shadow},rulesTitle:{fontSize:17,fontWeight:'900',color:colors.ink},rule:{flexDirection:'row',alignItems:'center',gap:10},ruleAmount:{width:52,height:36,lineHeight:36,textAlign:'center',borderRadius:18,overflow:'hidden',backgroundColor:colors.lilac,color:colors.purpleDark,fontWeight:'950'},ruleCopy:{flex:1,color:colors.ink,fontSize:13,lineHeight:18},note:{fontSize:10.5,lineHeight:15,color:colors.muted,marginTop:4},sectionHead:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},section:{fontSize:18,fontWeight:'900',color:colors.ink},meta:{fontSize:12,color:colors.muted},reward:{backgroundColor:colors.white,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,padding:16,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12,...shadow},partner:{fontSize:10,fontWeight:'900',letterSpacing:1,color:colors.purple},rewardTitle:{fontSize:17,fontWeight:'900',color:colors.ink,marginTop:4},rewardCopy:{fontSize:12.5,color:colors.muted,marginTop:4,maxWidth:240},cost:{backgroundColor:colors.purple,borderRadius:radius.pill,paddingVertical:9,paddingHorizontal:12},costText:{color:colors.white,fontWeight:'900'},entry:{backgroundColor:colors.white,borderRadius:radius.md,borderWidth:1,borderColor:colors.border,padding:14,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:10},entryText:{flex:1},entryReason:{fontSize:13.5,fontWeight:'750',color:colors.ink},entryDate:{fontSize:11,color:colors.muted,marginTop:3},entryAmount:{fontSize:17,fontWeight:'950',color:colors.success},negative:{color:colors.danger}});
