import AsyncStorage from '@react-native-async-storage/async-storage';
import { Redirect, router } from 'expo-router';
import { useEffect, useState } from 'react';
import { ImageBackground, StyleSheet, Text, View } from 'react-native';
import { BrandHeader, ParisWatermark } from '@/components/BrandHeader';
import { Button, Eyebrow, Loading, Title } from '@/components/ui';
import { colors, radius } from '@/theme';
const HERO='https://images.pexels.com/photos/34592097/pexels-photo-34592097.jpeg?auto=compress&cs=tinysrgb&w=1200';
export default function Onboarding(){const [seen,setSeen]=useState<boolean|null>(null);useEffect(()=>{AsyncStorage.getItem('onboarding:v1').then(v=>setSeen(v==='1'))},[]);if(seen===null)return <Loading/>;if(seen)return <Redirect href="/(tabs)"/>;const go=async(path:'/(tabs)'|'/auth')=>{await AsyncStorage.setItem('onboarding:v1','1');router.replace(path)};return <View style={s.page}><BrandHeader/><ImageBackground source={{uri:HERO}} style={s.hero} imageStyle={s.heroImage}><View style={s.shade}/><ParisWatermark dark/><View style={s.content}><Eyebrow inverse>BLACKSPOT YOU</Eyebrow><Title inverse>Des lieux. Des vécus. Une communauté.</Title><Text style={s.body}>Découvrez les adresses recommandées, documentez vos expériences et contribuez à une carte plus utile pour la communauté noire.</Text></View></ImageBackground><Button title="Découvrir les lieux" onPress={()=>go('/(tabs)')}/><Button title="Créer un compte ou se connecter" variant="secondary" onPress={()=>go('/auth')}/><Text style={s.note}>La géolocalisation est facultative et sert uniquement à afficher les spots à proximité.</Text></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas,padding:24,paddingTop:58,gap:16},hero:{flex:1,minHeight:420,borderRadius:radius.xl,overflow:'hidden',justifyContent:'flex-end'},heroImage:{borderRadius:radius.xl},shade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(13,9,17,.58)'},content:{padding:22,gap:12},body:{fontSize:16,lineHeight:24,color:'rgba(255,255,255,.84)'},note:{textAlign:'center',color:colors.muted,fontSize:11.5,marginTop:2}});
