import { router } from 'expo-router';
import { useEffect, useState } from 'react';
import { Alert, KeyboardAvoidingView, Platform, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { LocationPicker } from '@/components/LocationPicker';
import { Button, Field, Loading, Title } from '@/components/ui';
import { useAuth } from '@/contexts/AuthContext';
import { messageForError } from '@/lib/errors';
import { listCategories, proposePlace } from '@/services/places';
import { colors, radius } from '@/theme';
import type { Category } from '@/types';

type Point={latitude:number;longitude:number};
type Experience='positive'|'mixed'|'negative'|'incident'|'update';
const experiences: {value:Experience;label:string}[]=[{value:'positive',label:'Positive'},{value:'mixed',label:'Mitigée'},{value:'negative',label:'Négative'},{value:'incident',label:'Incident'},{value:'update',label:'Mise à jour'}];
const today=new Date().toISOString().slice(0,10);

export default function Propose(){
  const {user}=useAuth(); const [categories,setCategories]=useState<Category[]>([]); const [loading,setLoading]=useState(true);
  const [name,setName]=useState(''),[address,setAddress]=useState(''),[postal,setPostal]=useState(''),[city,setCity]=useState('');
  const [categoryId,setCategoryId]=useState<number|null>(null),[point,setPoint]=useState<Point|null>(null),[experience,setExperience]=useState<Experience>('positive');
  const [visitDate,setVisitDate]=useState(today),[title,setTitle]=useState(''),[body,setBody]=useState(''),[anonymous,setAnonymous]=useState(false),[contact,setContact]=useState(true),[busy,setBusy]=useState(false);
  useEffect(()=>{listCategories().then(setCategories).finally(()=>setLoading(false));},[]);
  if(!user)return <ScrollView contentContainerStyle={s.content}><Title>Proposer un lieu</Title><Text style={s.copy}>Un compte est nécessaire pour suivre votre proposition.</Text><Button title="Se connecter" onPress={()=>router.replace('/auth')}/></ScrollView>;
  if(loading)return <Loading/>;
  const valid=name.trim().length>=2&&city.trim().length>0&&categoryId!==null&&point!==null&&/^\d{4}-\d{2}-\d{2}$/.test(visitDate)&&body.trim().length>=20;
  const submit=async()=>{if(!valid||!point||categoryId===null)return;setBusy(true);try{await proposePlace({name:name.trim(),address_line:address.trim()||null,postal_code:postal.trim()||null,city:city.trim(),country_code:'FR',latitude:point.latitude,longitude:point.longitude,category_id:categoryId,experience_type:experience,visit_date:visitDate,title:title.trim(),body:body.trim(),is_anonymous:anonymous,contact_consent:contact});Alert.alert('Proposition envoyée','Le lieu et votre expérience restent privés jusqu’à leur validation par la modération.',[{text:'OK',onPress:()=>router.back()}]);}catch(e){Alert.alert('Envoi impossible',messageForError(e));}finally{setBusy(false);}};
  return <KeyboardAvoidingView behavior={Platform.OS==='ios'?'padding':undefined} style={s.page}><ScrollView contentContainerStyle={s.content} keyboardShouldPersistTaps="handled"><Title>Proposer un lieu</Title><Text style={s.copy}>Identifiez précisément le lieu et racontez une expérience sincère. Rien n’est publié automatiquement.</Text><Text style={s.section}>1 · LE LIEU</Text><Field label="Nom du lieu" value={name} onChangeText={setName}/><Field label="Adresse" value={address} onChangeText={setAddress}/><Field label="Code postal" value={postal} onChangeText={setPostal} keyboardType="number-pad"/><Field label="Ville" value={city} onChangeText={setCity}/><Text style={s.label}>Catégorie</Text><View style={s.chips}>{categories.map(category=><Pressable accessibilityRole="radio" accessibilityState={{selected:categoryId===category.id}} key={category.id} onPress={()=>setCategoryId(category.id)} style={[s.chip,categoryId===category.id&&s.chipActive]}><Text style={[s.chipText,categoryId===category.id&&s.chipTextActive]}>{category.label}</Text></Pressable>)}</View><Text style={s.label}>Emplacement exact</Text><LocationPicker value={point} onChange={setPoint}/><Text style={s.section}>2 · VOTRE EXPÉRIENCE</Text><Text style={s.label}>Type d’expérience</Text><View style={s.chips}>{experiences.map(item=><Pressable accessibilityRole="radio" accessibilityState={{selected:experience===item.value}} key={item.value} onPress={()=>setExperience(item.value)} style={[s.chip,experience===item.value&&s.chipActive]}><Text style={[s.chipText,experience===item.value&&s.chipTextActive]}>{item.label}</Text></Pressable>)}</View><Field label="Date de visite (AAAA-MM-JJ)" value={visitDate} onChangeText={setVisitDate}/><Field label="Titre facultatif" value={title} onChangeText={setTitle}/><Field label="Votre expérience (20 caractères minimum)" value={body} onChangeText={setBody} multiline/><Toggle label="Publier anonymement" value={anonymous} onValueChange={setAnonymous}/><Toggle label="Autoriser la modération à me contacter" value={contact} onValueChange={setContact}/><Button title={busy?'Envoi…':'Envoyer à la modération'} disabled={busy||!valid} onPress={()=>void submit()}/></ScrollView></KeyboardAvoidingView>;
}
function Toggle({label,value,onValueChange}:{label:string;value:boolean,onValueChange:(value:boolean)=>void}){return <View style={s.toggle}><Text style={s.toggleText}>{label}</Text><Switch accessibilityLabel={label} value={value} onValueChange={onValueChange} trackColor={{true:colors.purple}}/></View>}
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{padding:24,gap:8,paddingBottom:60},copy:{color:colors.muted,lineHeight:22,marginBottom:8},section:{fontWeight:'900',fontSize:13,letterSpacing:1.3,color:colors.purpleDark,marginTop:18},label:{fontSize:14,fontWeight:'700',color:colors.ink,marginTop:5},chips:{flexDirection:'row',flexWrap:'wrap',gap:8},chip:{borderWidth:1,borderColor:colors.border,borderRadius:radius.pill,paddingVertical:10,paddingHorizontal:13,backgroundColor:colors.white},chipActive:{backgroundColor:colors.purple,borderColor:colors.purple},chipText:{color:colors.ink,fontWeight:'700'},chipTextActive:{color:colors.white},toggle:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},toggleText:{flex:1,color:colors.ink,fontWeight:'600'}});
