import { router } from 'expo-router';
import { useCallback,useEffect,useMemo,useState } from 'react';
import { FlatList,Image,Linking,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native';
import { BrandHeader,ParisWatermark } from '@/components/BrandHeader';
import { Empty,Eyebrow,Loading,Title } from '@/components/ui';
import { listSpotlight } from '@/services/spotlight';
import { colors,radius,shadow } from '@/theme';
import type { SpotlightItem } from '@/types';

const label:Record<SpotlightItem['kind'],string>={favorite:'Nos favoris',partner:'Partenaire',event:'Événement',news:'Actualité',sponsored:'Sponsorisé'};
function openItem(item:SpotlightItem){if(item.establishments?.slug){router.push({pathname:'/place/[slug]',params:{slug:item.establishments.slug}});return;}if(item.link_url)void Linking.openURL(item.link_url);}
function FeatureCard({item}:{item:SpotlightItem}){return <Pressable onPress={()=>openItem(item)} style={({pressed})=>[s.feature,pressed&&s.pressed]}>
  {item.image_url?<Image source={{uri:item.image_url}} style={StyleSheet.absoluteFill} resizeMode="cover"/>:<View style={s.featureFallback}><ParisWatermark dark/><Text style={s.featureLetter}>{item.title.slice(0,1)}</Text></View>}
  <View style={s.featureShade}/><View style={s.featureContent}><Text style={s.featureTag}>{item.is_sponsored?'SPONSORISÉ':item.eyebrow??label[item.kind].toUpperCase()}</Text><Text style={s.featureTitle}>{item.title}</Text><Text numberOfLines={2} style={s.featureCopy}>{item.summary}</Text></View>
</Pressable>}
function FeedCard({item}:{item:SpotlightItem}){return <Pressable onPress={()=>openItem(item)} style={({pressed})=>[s.feed,pressed&&s.pressed]}><View style={s.feedArt}>{item.image_url?<Image source={{uri:item.image_url}} style={StyleSheet.absoluteFill} resizeMode="cover"/>:<Text style={s.feedLetter}>{item.title.slice(0,1)}</Text>}</View><View style={s.feedBody}><Text style={s.feedTag}>{item.is_sponsored?'Sponsorisé':label[item.kind]}</Text><Text style={s.feedTitle}>{item.title}</Text><Text numberOfLines={3} style={s.feedCopy}>{item.summary}</Text>{item.cta_label?<Text style={s.cta}>{item.cta_label} →</Text>:null}</View></Pressable>}
export default function Spotlight(){const [items,setItems]=useState<SpotlightItem[]>([]);const [loading,setLoading]=useState(true);const load=useCallback(()=>{setLoading(true);return listSpotlight().then(setItems).finally(()=>setLoading(false))},[]);useEffect(()=>{void load()},[load]);const priority=useMemo(()=>items.filter(i=>i.is_priority).slice(0,6),[items]);const feed=useMemo(()=>items.filter(i=>!i.is_priority),[items]);return <FlatList style={s.page} contentContainerStyle={s.content} data={feed} keyExtractor={i=>i.id} renderItem={({item})=><FeedCard item={item}/>} ListHeaderComponent={<View style={s.header}><BrandHeader/><View><Eyebrow>À LA UNE</Eyebrow><Title>Ce qui fait bouger l’écosystème BLACKSPOT YOU.</Title><Text style={s.intro}>Nos adresses favorites, les collaborations, les partenaires, les événements et les actualités sélectionnées par l’équipe.</Text></View>{loading?<Loading/>:priority.length?<><View style={s.sectionHead}><Text style={s.sectionTitle}>Sélection prioritaire</Text><Text style={s.sectionMeta}>{priority.length} mise{priority.length>1?'s':''} en avant</Text></View><ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={s.featureRow}>{priority.map(item=><FeatureCard key={item.id} item={item}/>)}</ScrollView></>:null}<View style={s.sectionHead}><Text style={s.sectionTitle}>Toutes les actus</Text><Text style={s.sectionMeta}>Mis à jour par l’équipe</Text></View></View>} ListEmptyComponent={!loading?<Empty text="Les prochaines actualités BLACKSPOT YOU apparaîtront ici."/>:null}/>} 
const s=StyleSheet.create({page:{flex:1,backgroundColor:colors.canvas},content:{padding:20,paddingTop:58,paddingBottom:120},header:{gap:18},intro:{color:colors.muted,fontSize:15,lineHeight:22,marginTop:8},sectionHead:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',gap:12,marginTop:2},sectionTitle:{fontSize:17,fontWeight:'900',color:colors.ink},sectionMeta:{fontSize:11,color:colors.muted},featureRow:{paddingRight:12,gap:12},feature:{width:282,height:310,borderRadius:radius.xl,overflow:'hidden',backgroundColor:colors.black,...shadow},featureFallback:{...StyleSheet.absoluteFillObject,backgroundColor:colors.black,justifyContent:'center',alignItems:'center'},featureLetter:{fontSize:120,fontWeight:'950',color:'rgba(109,40,217,.78)'},featureShade:{...StyleSheet.absoluteFillObject,backgroundColor:'rgba(11,8,14,.50)'},featureContent:{position:'absolute',left:18,right:18,bottom:18,gap:7},featureTag:{alignSelf:'flex-start',color:'#D9C8FF',fontWeight:'900',fontSize:10,letterSpacing:1.4},featureTitle:{color:colors.white,fontSize:25,fontWeight:'950'},featureCopy:{color:'rgba(255,255,255,.8)',fontSize:13,lineHeight:18},feed:{backgroundColor:colors.white,borderWidth:1,borderColor:colors.border,borderRadius:radius.lg,overflow:'hidden',marginVertical:8,flexDirection:'row',minHeight:150,...shadow},feedArt:{width:105,backgroundColor:colors.purpleDeep,alignItems:'center',justifyContent:'center',overflow:'hidden'},feedLetter:{fontSize:58,fontWeight:'950',color:'rgba(255,255,255,.9)'},feedBody:{flex:1,padding:14,gap:5},feedTag:{fontSize:10,color:colors.purple,fontWeight:'900',textTransform:'uppercase',letterSpacing:.8},feedTitle:{fontSize:18,fontWeight:'900',color:colors.ink},feedCopy:{fontSize:12.5,lineHeight:18,color:colors.muted},cta:{fontSize:12,color:colors.purple,fontWeight:'850',marginTop:2},pressed:{opacity:.85}});
