import type { PropsWithChildren } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, TextInput, type TextInputProps, View } from 'react-native';
import { colors, radius } from '@/theme';
export function Screen({ children }: PropsWithChildren) { return <View style={s.screen}>{children}</View>; }
export function Title({ children }: PropsWithChildren) { return <Text accessibilityRole="header" style={s.title}>{children}</Text>; }
export function Button({ title, onPress, disabled=false, variant='primary' }: { title:string; onPress:()=>void; disabled?:boolean; variant?:'primary'|'secondary'|'danger' }) { return <Pressable accessibilityRole="button" accessibilityLabel={title} disabled={disabled} onPress={onPress} style={[s.button, variant==='secondary'&&s.secondary, variant==='danger'&&s.danger, disabled&&s.disabled]}><Text style={[s.buttonText, variant==='secondary'&&s.secondaryText]}>{title}</Text></Pressable>; }
export function Field(props: TextInputProps & { label:string }) { return <View style={s.field}><Text style={s.label}>{props.label}</Text><TextInput {...props} accessibilityLabel={props.label} placeholderTextColor={colors.muted} style={[s.input, props.multiline&&s.multiline]} /></View>; }
export function Loading() { return <View style={s.center}><ActivityIndicator size="large" color={colors.purple}/><Text style={s.muted}>Chargement…</Text></View>; }
export function Empty({ text }: { text:string }) { return <View style={s.center}><Text style={s.muted}>{text}</Text></View>; }
const s=StyleSheet.create({screen:{flex:1,backgroundColor:colors.canvas,padding:20},title:{fontSize:30,fontWeight:'800',color:colors.ink,letterSpacing:-.7},button:{minHeight:52,borderRadius:radius.pill,backgroundColor:colors.purple,alignItems:'center',justifyContent:'center',paddingHorizontal:22,marginVertical:6},buttonText:{color:colors.white,fontWeight:'800',fontSize:16},secondary:{backgroundColor:colors.lilac},secondaryText:{color:colors.purpleDark},danger:{backgroundColor:colors.danger},disabled:{opacity:.5},field:{gap:7,marginVertical:8},label:{fontSize:14,fontWeight:'700',color:colors.ink},input:{minHeight:50,borderWidth:1,borderColor:colors.border,borderRadius:radius.md,paddingHorizontal:14,color:colors.ink,backgroundColor:colors.white,fontSize:16},multiline:{minHeight:110,paddingTop:14,textAlignVertical:'top'},center:{flex:1,alignItems:'center',justifyContent:'center',gap:12,padding:24},muted:{color:colors.muted,textAlign:'center'}});
